version: "3.9"
services:
  app:
    build: app/python/.
    container_name: web_app
    volumes:
      - ./app/web:/web
      - ./files:/files
    ports:
      - "5000:5000"
    networks:
      - sh-network
  nginx:
    image: nginx:latest
    container_name: web_proxy
    restart: unless-stopped
    volumes:
      - ./app/config/nginx.conf:/etc/nginx/nginx.conf
      - ./app/web:/www
    ports:
      - 9090:80
    networks:
      - sh-network

networks:
  sh-network: